appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: m0iYUdi7DcocG3r0AO3pkyDIuIb8Jlc95p06mgA+Qe0XPPsXZs3QGK/6P3FX8QuZTAotDipTpO4OzbTOt48GCxrvOIX43fYusq5qZik1yojg27zAy2TrzEZoYFEGzqvXVOJ03GrR6/Jna+x7zY5THcu6lVzYtUZim82CZOVycvsY73cMmfPAw45LmTq5DlDnj1sHNR8e/BnJ2RAIo+9C5uYTxu7uktOlbDsSpB0cGLfWHek8iKAz6/P1F4E8Vi2sULOMa2LZLO58RTJ3O9KV0XrHnz4MuViVAVMhCebUXpL16iUGBP4JFYHEZje1C1Gumk9vijNVhri1sQUIK5264ZyepHZJ2sWRdVQ464mNdbYC3iNkBZJiYvA2ptLsTlhpwizrfSe2isoTVULYfDFF4BBx416s50luyo3lXSUML9U807Xhp3khM7fmtJJIY7RXsypQZ9kTKYaGy3zlVCSsGavP5P9F3dJPo13ZOtdKWBUlfQt17u4ZeTxd7OtipqRzys2guIk20X/ASJ1tV0gKly7/2NIzT9p9l2msCfvc4LawosaHn6UWQnDQayq7CrYiNMb6ZXQrNVAgjcasKpAzEwIg+hZK4kHcb0p1nHg3o6mUUBN5vdhqbyIqWRq2muL8piV5BGyqJBkmY6VbOOVhCwq8vhV5s3fBT5Psor1JATw=}
